version: "3"
services:
  udagram-api-user:
    build:
      context: ../../udagram-api/user
    image: udagram-api-user
  udagram-api-feed:
    build:
      context: ../../udagram-api/feed
    image: udagram-api-feed
  udagram-frontend:
    build:
      context: ../../udagram-frontend
    image: udagram-frontend
  udagram-reverseproxy:
    build:
      context: .
    image: udagram-reverseproxy